execute pathogen#infect()
set nocompatible
filetype plugin indent on

map <space> <leader>

" Disable bell
set noeb vb t_vb=

set smarttab
set autoindent
set smartindent
set viminfo='10,\"100,:20,%

set nostartofline " Keep cursor in the same column if possible.
"set whichwrap=b,s,[,],<,>,h,l " Allow cursor to wrap between lines.
set lazyredraw " Don't redraw screen while executing macros/mappings.
set scrolloff=1 " Minimal number of screen lines to keep above and below the cursor.
set incsearch " Enable incremental search.
set backspace=indent,eol,start " Allow backspacing over everything in insert mode.
" set winaltkeys=no " Allow mapping of alt (meta) key shortcuts.
set ruler " Show the cursor position all the time.
set showcmd " Display incomplete commands.
set ignorecase smartcase " Ignore case when the pattern contains lowercase letters only.
set showtabline=1 " Show tab page labels if there is more than one tab.
set number " Display line numbers.
set shiftwidth=4 " Spaces for each step of (auto)indent
set tabstop=4 " Spaces that a <Tab> in the file counts for
set softtabstop=4 " Spaces that a <Tab> counts for when editing
" set cursorline " Shows what line the cursor is on
" set cursorcolumn " Shows what column the cursor is on
set mouse=a
" set showmatch

set notimeout
set ttimeout
set ttimeoutlen=100

" Folding
let g:xml_syntax_folding=1

set foldmethod=syntax
set foldlevelstart=20

colorscheme elflord

" File Type handling

au!

au BufNewFile,BufRead *.glsl,*.vert,*.frag,*.geom set syntax=glsl noexpandtab shiftwidth=4 softtabstop=4 tabstop=4
au BufNewFile,BufRead *.rl set syntax=ragel cindent noexpandtab shiftwidth=4 softtabstop=4 tabstop=4
au BufNewFile,BufRead *.cl set syntax=opencl noexpandtab tabstop=2 shiftwidth=2 softtabstop=2
au BufRead,BufNewFile *.rb,*.rhtml,*.haml,Gemfile,Rakefile,Vagrantfile,Thorfile,config.ru,*.slim,*.yml set expandtab tabstop=2 shiftwidth=2 softtabstop=2 syntax=ruby
au BufRead,BufNewFile *.py set expandtab shiftwidth=4 softtabstop=4 tabstop=4
au BufRead,BufNewFile *.haml         setfiletype haml
au BufRead,BufNewFile {Gemfile,Rakefile,Vagrantfile,Thorfile,config.ru} set ft=ruby
au BufRead,BufNewFile {*.json} set ft=javascript noexpandtab shiftwidth=4 softtabstop=4 tabstop=4
au BufRead,BufNewFile *.js set noexpandtab shiftwidth=4 softtabstop=4 tabstop=4
au BufRead,BufNewFile *.ffs set syntax=cpp
au BufRead,BufNewFile *.c,*.cpp,*.h,*.hpp,*.ffs,*.ddf set cindent noexpandtab shiftwidth=4 softtabstop=4 tabstop=4
au BufRead,BufNewFile *.php set ft=php noexpandtab shiftwidth=4 softtabstop=4 tabstop=4
au BufRead,BufNewFile *.yaml,*.yml,*.anim,*.preset,*.conf set expandtab shiftwidth=2 softtabstop=2 tabstop=2 syntax=yaml

" Bindings


" Don't remove visual block when indenting.
"vmap < <gv
"vmap > >gv

set pastetoggle=<F2>

" Copy paste with leader
vmap <Leader>y "+y
vmap <Leader>d "+d
nmap <Leader>p "+p
nmap <Leader>P "+P
vmap <Leader>p "+p
vmap <Leader>P "+P

"This allows for change paste motion cp{motion}
nmap <silent> cp :set opfunc=ChangePaste<CR>g@
function! ChangePaste(type, ...)
    silent exe "normal! `[v`]\"_c"
    silent exe "normal! p"
endfunction

" Some nerdtree setup
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTreeType") && b:NERDTreeType == "primary") | q | endif

" And turn on the syntax!
syntax on
